# This file was generated by GoReleaser. DO NOT EDIT.
class Citool < Formula
  desc "Pinpoint CI Tool is a utility to collect and deliver CI/CD details to the Pinpoint Cloud"
  homepage "https://pinpoint.com"
  version "0.0.1"

  if OS.mac?
    url "https://github.com/pinpt/citool/releases/download/0.0.1/citool_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "2a69f035fcc5c28ba0d5acde1c2a65065d2eea2b75650c5bf9c8e69861e2ac2d"
  elsif OS.linux?
    url "https://github.com/pinpt/citool/releases/download/0.0.1/citool_0.0.1_Linux_x86_64.tar.gz"
    sha256 "586ed7ae72869687c3d8eb0f09256312ef3213d74649a8828ff68e3f62dde200"
  end

  def install
    bin.install "citool"
  end
end
